name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'static'
        destination_repo: 'mnicholstamu/test-repo'
        destination_folder: 'test-dir'
        user_email: 'mnichols@tamu.edu'
        user_name: 'mnicholstamu'
        commit_message: 'A custom message for the commit'
